# Generated by Django 3.1.1 on 2020-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
