# Generated by Django 3.1.1 on 2020-10-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201008_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
    ]
