# Generated by Django 3.1.1 on 2020-10-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201018_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
